# --- Basic Site Settings ---
title: Fariya Asghar
tagline: Data Analyst | Transforming Data into Actionable Insights
description: A professional portfolio showcasing data analysis and visualization projects.
url: "https://fariyaasghar.github.io"
#baseurl: "/portfolio" # Correctly commented out for local development

# --- Theme ---
theme: jekyll-theme-chirpy

# --- Author & Social Links ---
avatar: /assets/images/avatar.jpg
social:
  name: Fariya Asghar
  email: fasghar91@gmail.com
  platforms:
    - name: github
      url: "https://github.com/fariyaasghar"
    - name: linkedin
      url: "https://www.linkedin.com/in/fariya-asghar"

# --- CRITICAL SECTION: Collections & Defaults ---
# This tells Jekyll to build your pages from the _tabs folder.
collections:
  tabs:
    output: true
    sort_by: order

# This tells Jekyll how to handle your case studies (_posts) and your pages (_tabs).
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/ # This creates clean URLs like /projects/
# Custom CSS
sass:
  sass_dir: _sass
  style: compressed


