# --- Basic Site Settings ---
title: Fariya Asghar
tagline: Data Analyst | Transforming Data into Actionable Insights
description: A professional portfolio showcasing data analysis and visualization projects.
url: "https://fariyaasghar.github.io"
baseurl: "/portfolio" # Correctly commented out for local development

# --- Theme ---
theme: jekyll-theme-chirpy

# --- Author & Social Links ---
avatar: /assets/images/avatar.jpg
social:
  name: Fariya Asghar
# --- CRITICAL SECTION: Collections & Defaults ---
# This tells Jekyll to build your pages from the _tabs folder.
collections:
  tabs:
    output: true
    sort_by: order

# This tells Jekyll how to handle your case studies (_posts) and your pages (_tabs).
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/ # This creates clean URLs like /projects/
# Custom CSS
sass:
  sass_dir: _sass
  style: compressed
# --- Footer Settings ---
# Disable the theme's default footer to use our custom one.
footer:
  show_copyright: false
  show_theme_info: false
# --- Jekyll Archives Plugin Configuration ---
# This enables the creation of pages for each tag and category.

jekyll-archives:
  enabled:
    - tags
    - categories
  layouts:
    tag: tag      # Use the 'tag.html' layout for tag pages
    category: category # Use the 'category.html' layout for category pages
  permalinks:
    tag: '/tags/:name/'
    category: '/categories/:name/'

# Web Analytics Settings
analytics:
  google:
    id: G-WYK88ZJJ97  # <-- PASTE YOUR ID HERE
  goatcounter:
    id: # fill in your GoatCounter ID